version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fueling-diary
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: